// import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import theme from "../theme/index"
import { ChakraProvider } from '@chakra-ui/react'
import Layout from '@/components/layout'
import Head from 'next/head'


export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>  
      <Layout>
      <Head>
        <title>Pick Click Move</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="activity.svg" />
      </Head>
        <Component {...pageProps} />
      </Layout>
    </ChakraProvider>
  )
}
